name: 'master'
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set-up Node with .nvmrc
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-
      - run: |
          npm ci
          npm run build
          npm run format-check
          npm run lint
          npm run package
          npm run test
      - name: Check for changes (fail if we forgot to update lib output)
        run: git diff --quiet dist
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: tradeshift/actions-semantic-release@v1
        id: semantic-release
        with:
          check_name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Action tags (major version tag)
        if: ${{ steps.semantic-release.outputs.new_release_published }}
        run: |
          git tag -f v${{ steps.semantic-release.outputs.new_release_major_version }}
          git push -f origin v${{ steps.semantic-release.outputs.new_release_major_version }}